version: '3.1'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rufet
      POSTGRES_PASSWORD: rufet
      POSTGRES_DB: rufet
    ports:
      - "5432:5432"